### PR TITLE
Feature/new member

### PR DESCRIPTION
**Pull request by medson10**

### CODE REVIEW

**Comment by medson10** [comment]
image

**Comment by medson10** [comment]
image

**Comment by medson10** [comment]
image

**Comment by guilhermedecampo** [comment]
awesome @medson10! Can you please get your avatar "squared"?

**Review by fakenickels — COMMENTED** [review]
:shipit:

**Review by fakenickels — APPROVED** [review]

**Review by guilhermedecampo — APPROVED** [review]
:top:

**Pull request merged**
