### PR TITLE
Add Eliabe to the Team

### PR DESCRIPTION
**Pull request by eliabejr**

### CODE REVIEW

**Comment by guilhermedecampo** [comment]
Awesome, how it looks like? Can you take some screenshots?

**Comment by eliabejr** [comment]
Team Section preview:

team

**Comment by eliabejr** [comment]
Astrocoders tab with favicon:

with-favicon

**Comment by guilhermedecampo** [comment]
Awesome thanks!

**Review by guilhermedecampo — APPROVED** [review]

**Comment by guilhermedecampo** [comment]
:shipit:

**Pull request merged**
